version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: 0.0.0.0:5000
  secret: somesecretkey
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3